/* eslint-disable */
// This file is auto-generated by @hey-api/openapi-ts

import {
  type DefaultError,
  type InfiniteData,
  infiniteQueryOptions,
  queryOptions,
  type UseMutationOptions,
} from '@tanstack/react-query'

import {client} from '../client.gen'
import {createFeed, deleteFeed, getArticle, listArticles, listFeeds, type Options, updateFeed} from '../sdk.gen'
import type {
  CreateFeedData,
  CreateFeedResponse,
  DeleteFeedData,
  DeleteFeedResponse,
  GetArticleData,
  GetArticleResponse,
  ListArticlesData,
  ListArticlesResponse,
  ListFeedsData,
  ListFeedsResponse,
  UpdateFeedData,
  UpdateFeedResponse,
} from '../types.gen'

export type QueryKey<TOptions extends Options> = [
  Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
    _id: string
    _infinite?: boolean
    tags?: ReadonlyArray<string>
  },
]

const createQueryKey = <TOptions extends Options>(
  id: string,
  options?: TOptions,
  infinite?: boolean,
  tags?: ReadonlyArray<string>
): [QueryKey<TOptions>[0]] => {
  const params: QueryKey<TOptions>[0] = {
    _id: id,
    baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl,
  } as QueryKey<TOptions>[0]
  if (infinite) {
    params._infinite = infinite
  }
  if (tags) {
    params.tags = tags
  }
  if (options?.body) {
    params.body = options.body
  }
  if (options?.headers) {
    params.headers = options.headers
  }
  if (options?.path) {
    params.path = options.path
  }
  if (options?.query) {
    params.query = options.query
  }
  return [params]
}

export const listFeedsQueryKey = (options?: Options<ListFeedsData>) => createQueryKey('listFeeds', options)

/**
 * List feeds
 */
export const listFeedsOptions = (options?: Options<ListFeedsData>) =>
  queryOptions<ListFeedsResponse, DefaultError, ListFeedsResponse, ReturnType<typeof listFeedsQueryKey>>({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await listFeeds({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listFeedsQueryKey(options),
  })

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(
  queryKey: QueryKey<Options>,
  page: K
) => {
  const params = {...queryKey[0]}
  if (page.body) {
    params.body = {
      ...(queryKey[0].body as any),
      ...(page.body as any),
    }
  }
  if (page.headers) {
    params.headers = {
      ...queryKey[0].headers,
      ...page.headers,
    }
  }
  if (page.path) {
    params.path = {
      ...(queryKey[0].path as any),
      ...(page.path as any),
    }
  }
  if (page.query) {
    params.query = {
      ...(queryKey[0].query as any),
      ...(page.query as any),
    }
  }
  return params as unknown as typeof page
}

export const listFeedsInfiniteQueryKey = (options?: Options<ListFeedsData>): QueryKey<Options<ListFeedsData>> =>
  createQueryKey('listFeeds', options, true)

/**
 * List feeds
 */
export const listFeedsInfiniteOptions = (options?: Options<ListFeedsData>) =>
  infiniteQueryOptions<
    ListFeedsResponse,
    DefaultError,
    InfiniteData<ListFeedsResponse>,
    QueryKey<Options<ListFeedsData>>,
    string | Pick<QueryKey<Options<ListFeedsData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({pageParam, queryKey, signal}) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListFeedsData>>[0], 'body' | 'headers' | 'path' | 'query'> =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const {data} = await listFeeds({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listFeedsInfiniteQueryKey(options),
    }
  )

/**
 * Create feed
 */
export const createFeedMutation = (
  options?: Partial<Options<CreateFeedData>>
): UseMutationOptions<CreateFeedResponse, DefaultError, Options<CreateFeedData>> => {
  const mutationOptions: UseMutationOptions<CreateFeedResponse, DefaultError, Options<CreateFeedData>> = {
    mutationFn: async fnOptions => {
      const {data} = await createFeed({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Delete feed
 */
export const deleteFeedMutation = (
  options?: Partial<Options<DeleteFeedData>>
): UseMutationOptions<DeleteFeedResponse, DefaultError, Options<DeleteFeedData>> => {
  const mutationOptions: UseMutationOptions<DeleteFeedResponse, DefaultError, Options<DeleteFeedData>> = {
    mutationFn: async fnOptions => {
      const {data} = await deleteFeed({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

/**
 * Update feed
 */
export const updateFeedMutation = (
  options?: Partial<Options<UpdateFeedData>>
): UseMutationOptions<UpdateFeedResponse, DefaultError, Options<UpdateFeedData>> => {
  const mutationOptions: UseMutationOptions<UpdateFeedResponse, DefaultError, Options<UpdateFeedData>> = {
    mutationFn: async fnOptions => {
      const {data} = await updateFeed({
        ...options,
        ...fnOptions,
        throwOnError: true,
      })
      return data
    },
  }
  return mutationOptions
}

export const listArticlesQueryKey = (options?: Options<ListArticlesData>) => createQueryKey('listArticles', options)

/**
 * List articles
 */
export const listArticlesOptions = (options?: Options<ListArticlesData>) =>
  queryOptions<ListArticlesResponse, DefaultError, ListArticlesResponse, ReturnType<typeof listArticlesQueryKey>>({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await listArticles({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: listArticlesQueryKey(options),
  })

export const listArticlesInfiniteQueryKey = (
  options?: Options<ListArticlesData>
): QueryKey<Options<ListArticlesData>> => createQueryKey('listArticles', options, true)

/**
 * List articles
 */
export const listArticlesInfiniteOptions = (options?: Options<ListArticlesData>) =>
  infiniteQueryOptions<
    ListArticlesResponse,
    DefaultError,
    InfiniteData<ListArticlesResponse>,
    QueryKey<Options<ListArticlesData>>,
    string | Pick<QueryKey<Options<ListArticlesData>>[0], 'body' | 'headers' | 'path' | 'query'>
  >(
    // @ts-ignore
    {
      queryFn: async ({pageParam, queryKey, signal}) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<ListArticlesData>>[0], 'body' | 'headers' | 'path' | 'query'> =
          typeof pageParam === 'object'
            ? pageParam
            : {
                query: {
                  cursor: pageParam,
                },
              }
        const params = createInfiniteParams(queryKey, page)
        const {data} = await listArticles({
          ...options,
          ...params,
          signal,
          throwOnError: true,
        })
        return data
      },
      queryKey: listArticlesInfiniteQueryKey(options),
    }
  )

export const getArticleQueryKey = (options: Options<GetArticleData>) => createQueryKey('getArticle', options)

/**
 * Get article
 */
export const getArticleOptions = (options: Options<GetArticleData>) =>
  queryOptions<GetArticleResponse, DefaultError, GetArticleResponse, ReturnType<typeof getArticleQueryKey>>({
    queryFn: async ({queryKey, signal}) => {
      const {data} = await getArticle({
        ...options,
        ...queryKey[0],
        signal,
        throwOnError: true,
      })
      return data
    },
    queryKey: getArticleQueryKey(options),
  })
