/* eslint-disable */
// This file is auto-generated by @hey-api/openapi-ts

import type {Client, Options as Options2, TDataShape} from './client'
import {client} from './client.gen'
import type {
  CreateFeedData,
  CreateFeedResponses,
  DeleteFeedData,
  DeleteFeedResponses,
  GetArticleData,
  GetArticleResponses,
  ListArticlesData,
  ListArticlesResponses,
  ListFeedsData,
  ListFeedsResponses,
} from './types.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * List feeds
 */
export const listFeeds = <ThrowOnError extends boolean = false>(options?: Options<ListFeedsData, ThrowOnError>) =>
  (options?.client ?? client).get<ListFeedsResponses, unknown, ThrowOnError>({url: '/api/feeds', ...options})

/**
 * Create feed
 */
export const createFeed = <ThrowOnError extends boolean = false>(options: Options<CreateFeedData, ThrowOnError>) =>
  (options.client ?? client).post<CreateFeedResponses, unknown, ThrowOnError>({
    url: '/api/feeds',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  })

/**
 * Delete feed
 */
export const deleteFeed = <ThrowOnError extends boolean = false>(options: Options<DeleteFeedData, ThrowOnError>) =>
  (options.client ?? client).delete<DeleteFeedResponses, unknown, ThrowOnError>({url: '/api/feeds/:id', ...options})

/**
 * List articles
 */
export const listArticles = <ThrowOnError extends boolean = false>(options?: Options<ListArticlesData, ThrowOnError>) =>
  (options?.client ?? client).get<ListArticlesResponses, unknown, ThrowOnError>({url: '/api/articles', ...options})

/**
 * Get article
 */
export const getArticle = <ThrowOnError extends boolean = false>(options: Options<GetArticleData, ThrowOnError>) =>
  (options.client ?? client).get<GetArticleResponses, unknown, ThrowOnError>({url: '/api/articles/:id', ...options})
