/* eslint-disable */
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:4000' | (string & {})
}

export type Feed = {
  id: string
  url: string
  title: string | null
  description: string | null
  iconUrl: string | null
  language: string | null
  error: string | null
  lastPullAt: string | null
  createdAt: string
}

export type Article = {
  id: string
  feedId: string | null
  url: string
  title: string
  description: string | null
  author: string | null
  imageUrl: string | null
  createdAt: string
  updatedAt: string | null
  feed: {
    id: string
    title: string | null
    url: string
    iconUrl: string | null
  } | null
}

export type ArticleWithContent = {
  id: string
  feedId: string | null
  url: string
  title: string
  description: string | null
  author: string | null
  imageUrl: string | null
  createdAt: string
  updatedAt: string | null
  feed: {
    id: string
    title: string | null
    url: string
    iconUrl: string | null
  } | null
  content: string | null
  wordsCount: number | null
}

export type ListFeedsData = {
  body?: never
  path?: never
  query?: {
    limit?: number | null
    cursor?: string
    dir?: 'asc' | 'desc'
  }
  url: '/api/feeds'
}

export type ListFeedsResponses = {
  /**
   * List of feeds.
   */
  200: {
    feeds: Array<Feed>
    cursor: string | null
    count: number
  }
}

export type ListFeedsResponse = ListFeedsResponses[keyof ListFeedsResponses]

export type CreateFeedData = {
  body: {
    url: string
  }
  path?: never
  query?: never
  url: '/api/feeds'
}

export type CreateFeedResponses = {
  /**
   * Feed created & validated.
   */
  200: {
    feed: Feed
  }
}

export type CreateFeedResponse = CreateFeedResponses[keyof CreateFeedResponses]

export type DeleteFeedData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/feeds/{id}'
}

export type DeleteFeedResponses = {
  /**
   * Feed deleted.
   */
  204: void
}

export type DeleteFeedResponse = DeleteFeedResponses[keyof DeleteFeedResponses]

export type UpdateFeedData = {
  body?: {
    url?: string
    title?: string
    description?: string
  }
  path: {
    id: string
  }
  query?: never
  url: '/api/feeds/{id}'
}

export type UpdateFeedResponses = {
  /**
   * Feed updated.
   */
  200: {
    feed: Feed
  }
}

export type UpdateFeedResponse = UpdateFeedResponses[keyof UpdateFeedResponses]

export type ListArticlesData = {
  body?: never
  path?: never
  query?: {
    limit?: number | null
    cursor?: string
    dir?: 'asc' | 'desc'
    sort?: 'id' | 'updatedAt'
  }
  url: '/api/articles'
}

export type ListArticlesResponses = {
  /**
   * List of articles.
   */
  200: {
    articles: Array<Article>
    cursor: string | null
    count: number
  }
}

export type ListArticlesResponse = ListArticlesResponses[keyof ListArticlesResponses]

export type GetArticleData = {
  body?: never
  path: {
    id: string
  }
  query?: never
  url: '/api/articles/{id}'
}

export type GetArticleResponses = {
  /**
   * Article details.
   */
  200: {
    article: ArticleWithContent
  }
}

export type GetArticleResponse = GetArticleResponses[keyof GetArticleResponses]
