// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:4000' | (string & {});
};

export type Feed = {
    id: string;
    url: string;
    lastPullAt: string | null;
    createdAt: string;
};

export type CreateFeedData = {
    body: {
        url: string;
    };
    path?: never;
    query?: never;
    url: '/feeds';
};

export type CreateFeedResponses = {
    /**
     * Create category
     */
    200: {
        feed: Feed;
    };
};

export type CreateFeedResponse = CreateFeedResponses[keyof CreateFeedResponses];
