/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashRouteRouteImport } from './routes/dash/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashIndexRouteImport } from './routes/dash/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashFeedsRouteImport } from './routes/dash/feeds'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'

const DashRouteRoute = DashRouteRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashIndexRoute = DashIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashRouteRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashFeedsRoute = DashFeedsRouteImport.update({
  id: '/feeds',
  path: '/feeds',
  getParentRoute: () => DashRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dash': typeof DashRouteRouteWithChildren
  '/auth/signup': typeof AuthSignupRoute
  '/dash/feeds': typeof DashFeedsRoute
  '/auth/': typeof AuthIndexRoute
  '/dash/': typeof DashIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dash/feeds': typeof DashFeedsRoute
  '/auth': typeof AuthIndexRoute
  '/dash': typeof DashIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dash': typeof DashRouteRouteWithChildren
  '/auth/signup': typeof AuthSignupRoute
  '/dash/feeds': typeof DashFeedsRoute
  '/auth/': typeof AuthIndexRoute
  '/dash/': typeof DashIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dash'
    | '/auth/signup'
    | '/dash/feeds'
    | '/auth/'
    | '/dash/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth/signup' | '/dash/feeds' | '/auth' | '/dash'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dash'
    | '/auth/signup'
    | '/dash/feeds'
    | '/auth/'
    | '/dash/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashRouteRoute: typeof DashRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dash': {
      id: '/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dash/': {
      id: '/dash/'
      path: '/'
      fullPath: '/dash/'
      preLoaderRoute: typeof DashIndexRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dash/feeds': {
      id: '/dash/feeds'
      path: '/feeds'
      fullPath: '/dash/feeds'
      preLoaderRoute: typeof DashFeedsRouteImport
      parentRoute: typeof DashRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthSignupRoute: typeof AuthSignupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSignupRoute: AuthSignupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashRouteRouteChildren {
  DashFeedsRoute: typeof DashFeedsRoute
  DashIndexRoute: typeof DashIndexRoute
}

const DashRouteRouteChildren: DashRouteRouteChildren = {
  DashFeedsRoute: DashFeedsRoute,
  DashIndexRoute: DashIndexRoute,
}

const DashRouteRouteWithChildren = DashRouteRoute._addFileChildren(
  DashRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashRouteRoute: DashRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
